qpu_threshold: 40
classical_threshold: 20
fci_threshold: 6
ewf_bath_type: mp2
ewf_truncation: 1.0e-05
spiral_chunk_size: 1000
spiral_max_gates: 100000
num_layouts: 10
beta: 0.001
min_count: 1
use_spiral: true
real_qpu: false
backend: null
shots: 100000
connectivity: heavy-hex
lucj_reps: 2
lucj_tol: 1.0e-05
lucj_optimize: false
lucj_method: L-BFGS-B
trim_fraction: 0.1
trim_stop_tol: 0.0001
reference_threshold: 30
reference_fci_threshold: 10
